// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';

export function GenerateNumbers(arg1:string):Promise<Array<string>>;

export function GetManualNumbers(arg1:string):Promise<Array<model.ManualNumber>>;

export function GetNumberSettings(arg1:string):Promise<model.NumberSettings>;

export function Init(arg1:service.NumberingService):Promise<void>;

export function ParseManualInput(arg1:string):Promise<Array<string>>;

export function SaveManualNumbers(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveNumberItems(arg1:string,arg2:Array<model.NumberItem>):Promise<void>;

export function SaveNumberSettings(arg1:model.NumberSettings):Promise<void>;

export function ValidateManualNumbers(arg1:Array<string>):Promise<model.ValidationResult>;
