// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateNumbers(arg1) {
  return window['go']['handler']['NumberingHandler']['GenerateNumbers'](arg1);
}

export function GetManualNumbers(arg1) {
  return window['go']['handler']['NumberingHandler']['GetManualNumbers'](arg1);
}

export function GetNumberSettings(arg1) {
  return window['go']['handler']['NumberingHandler']['GetNumberSettings'](arg1);
}

export function Init(arg1) {
  return window['go']['handler']['NumberingHandler']['Init'](arg1);
}

export function ParseManualInput(arg1) {
  return window['go']['handler']['NumberingHandler']['ParseManualInput'](arg1);
}

export function SaveManualNumbers(arg1, arg2) {
  return window['go']['handler']['NumberingHandler']['SaveManualNumbers'](arg1, arg2);
}

export function SaveNumberSettings(arg1) {
  return window['go']['handler']['NumberingHandler']['SaveNumberSettings'](arg1);
}

export function ValidateManualNumbers(arg1) {
  return window['go']['handler']['NumberingHandler']['ValidateManualNumbers'](arg1);
}
