// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['handler']['ProjectHandler']['CreateProject'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['handler']['ProjectHandler']['DeleteProject'](arg1);
}

export function DuplicateProject(arg1) {
  return window['go']['handler']['ProjectHandler']['DuplicateProject'](arg1);
}

export function GetAssetDataUrl(arg1, arg2) {
  return window['go']['handler']['ProjectHandler']['GetAssetDataUrl'](arg1, arg2);
}

export function GetProject(arg1) {
  return window['go']['handler']['ProjectHandler']['GetProject'](arg1);
}

export function GetProjectAssets(arg1) {
  return window['go']['handler']['ProjectHandler']['GetProjectAssets'](arg1);
}

export function GetProjectFull(arg1) {
  return window['go']['handler']['ProjectHandler']['GetProjectFull'](arg1);
}

export function GetRecentProjects() {
  return window['go']['handler']['ProjectHandler']['GetRecentProjects']();
}

export function ImportImage(arg1) {
  return window['go']['handler']['ProjectHandler']['ImportImage'](arg1);
}

export function Init(arg1, arg2, arg3) {
  return window['go']['handler']['ProjectHandler']['Init'](arg1, arg2, arg3);
}

export function ListProjects() {
  return window['go']['handler']['ProjectHandler']['ListProjects']();
}

export function SaveExportedPDF(arg1, arg2) {
  return window['go']['handler']['ProjectHandler']['SaveExportedPDF'](arg1, arg2);
}

export function UpdateProject(arg1) {
  return window['go']['handler']['ProjectHandler']['UpdateProject'](arg1);
}
