// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';
import {service} from '../models';

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<model.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function DuplicateProject(arg1:string):Promise<model.Project>;

export function GetAssetDataUrl(arg1:string,arg2:string):Promise<string>;

export function GetProject(arg1:string):Promise<model.Project>;

export function GetProjectAssets(arg1:string):Promise<Array<model.Asset>>;

export function GetProjectFull(arg1:string):Promise<model.ProjectFull>;

export function GetRecentProjects():Promise<Array<model.Project>>;

export function ImportImage(arg1:string):Promise<model.Asset>;

export function Init(arg1:context.Context,arg2:service.ProjectService,arg3:service.StorageService):Promise<void>;

export function ListProjects():Promise<Array<model.Project>>;

export function SaveExportedPDF(arg1:string,arg2:string):Promise<string>;

export function UpdateProject(arg1:model.Project):Promise<void>;
