// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';

export function CalculateSheet(arg1:string,arg2:number):Promise<model.SheetLayout>;

export function GetCropBleedSettings(arg1:string):Promise<model.CropBleedSettings>;

export function GetSheetSettings(arg1:string):Promise<model.SheetSettings>;

export function Init(arg1:service.SheetService):Promise<void>;

export function SaveCropBleedSettings(arg1:model.CropBleedSettings):Promise<void>;

export function SaveSheetSettings(arg1:model.SheetSettings):Promise<void>;
