// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateSheet(arg1, arg2) {
  return window['go']['handler']['SheetHandler']['CalculateSheet'](arg1, arg2);
}

export function GetCropBleedSettings(arg1) {
  return window['go']['handler']['SheetHandler']['GetCropBleedSettings'](arg1);
}

export function GetSheetSettings(arg1) {
  return window['go']['handler']['SheetHandler']['GetSheetSettings'](arg1);
}

export function Init(arg1) {
  return window['go']['handler']['SheetHandler']['Init'](arg1);
}

export function SaveCropBleedSettings(arg1) {
  return window['go']['handler']['SheetHandler']['SaveCropBleedSettings'](arg1);
}

export function SaveSheetSettings(arg1) {
  return window['go']['handler']['SheetHandler']['SaveSheetSettings'](arg1);
}
