package handler

import (
	"context"
	"encoding/base64"
	"fmt"
	"os"
	"strings"

	"github.com/abhinandpn/Recipta/backend/model"
	"github.com/abhinandpn/Recipta/backend/service"
	"github.com/wailsapp/wails/v2/pkg/runtime"
)

// SaveExportedPDF opens a native save dialog and writes a PDF generated by the editor.
func (h *ProjectHandler) SaveExportedPDF(suggestedName string, encodedPDF string) (string, error) {
	filePath, err := runtime.SaveFileDialog(h.ctx, runtime.SaveDialogOptions{
		Title:           "Export Numbered PDF",
		DefaultFilename: suggestedName,
		Filters:         []runtime.FileFilter{{DisplayName: "PDF Document (*.pdf)", Pattern: "*.pdf"}},
	})
	if err != nil || filePath == "" {
		return filePath, err
	}
	if !strings.HasSuffix(strings.ToLower(filePath), ".pdf") {
		filePath += ".pdf"
	}
	data, err := base64.StdEncoding.DecodeString(encodedPDF)
	if err != nil {
		return "", fmt.Errorf("invalid PDF data: %w", err)
	}
	if err := os.WriteFile(filePath, data, 0644); err != nil {
		return "", fmt.Errorf("failed to save PDF: %w", err)
	}
	return filePath, nil
}

// ProjectHandler exposes project operations to the frontend via Wails bindings.
type ProjectHandler struct {
	ctx            context.Context
	projectService *service.ProjectService
	storageService *service.StorageService
}

// Init wires the handler's dependencies. Called during app startup.
func (h *ProjectHandler) Init(ctx context.Context, projectService *service.ProjectService, storageService *service.StorageService) {
	h.ctx = ctx
	h.projectService = projectService
	h.storageService = storageService
}

// CreateProject creates a new project.
func (h *ProjectHandler) CreateProject(name string, projectType string, description string) (*model.Project, error) {
	return h.projectService.CreateProject(name, model.ProjectType(projectType), description)
}

// GetProject retrieves a project by ID.
func (h *ProjectHandler) GetProject(id string) (*model.Project, error) {
	return h.projectService.GetProject(id)
}

// GetProjectFull retrieves a project with all related settings.
func (h *ProjectHandler) GetProjectFull(id string) (*model.ProjectFull, error) {
	return h.projectService.GetProjectFull(id)
}

// ListProjects returns all projects.
func (h *ProjectHandler) ListProjects() ([]*model.Project, error) {
	return h.projectService.ListProjects()
}

// GetRecentProjects returns recently opened projects.
func (h *ProjectHandler) GetRecentProjects() ([]*model.Project, error) {
	return h.projectService.GetRecentProjects(10)
}

// UpdateProject updates project metadata.
func (h *ProjectHandler) UpdateProject(project *model.Project) error {
	return h.projectService.UpdateProject(project)
}

// DeleteProject removes a project.
func (h *ProjectHandler) DeleteProject(id string) error {
	return h.projectService.DeleteProject(id)
}

// DuplicateProject creates a copy of an existing project.
func (h *ProjectHandler) DuplicateProject(id string) (*model.Project, error) {
	return h.projectService.DuplicateProject(id)
}

// ImportImage opens a file dialog for the user to select an image or PDF, then imports it.
func (h *ProjectHandler) ImportImage(projectID string) (*model.Asset, error) {
	// Open native file dialog with PDF and All Image Formats
	filePath, err := runtime.OpenFileDialog(h.ctx, runtime.OpenDialogOptions{
		Title: "Import Template (Images & PDF)",
		Filters: []runtime.FileFilter{
			{
				DisplayName: "All Supported Templates (*.png;*.jpg;*.jpeg;*.pdf;*.svg;*.webp;*.bmp;*.tiff)",
				Pattern:     "*.png;*.jpg;*.jpeg;*.pdf;*.svg;*.webp;*.bmp;*.gif;*.tiff;*.tif",
			},
			{
				DisplayName: "PDF Documents (*.pdf)",
				Pattern:     "*.pdf",
			},
			{
				DisplayName: "Images (*.png;*.jpg;*.jpeg;*.svg;*.webp;*.bmp)",
				Pattern:     "*.png;*.jpg;*.jpeg;*.svg;*.webp;*.bmp;*.gif;*.tiff;*.tif",
			},
			{
				DisplayName: "All Files (*.*)",
				Pattern:     "*.*",
			},
		},
	})
	if err != nil {
		return nil, err
	}
	if filePath == "" {
		return nil, nil // User cancelled
	}

	return h.storageService.ImportImage(projectID, filePath)
}

// GetAssetDataUrl reads the stored asset file and returns it as a Base64 data URL.
func (h *ProjectHandler) GetAssetDataUrl(projectID string, assetID string) (string, error) {
	return h.storageService.GetAssetDataUrl(assetID, projectID)
}

// GetProjectAssets retrieves all assets for a project.
func (h *ProjectHandler) GetProjectAssets(projectID string) ([]*model.Asset, error) {
	return h.storageService.GetProjectAssets(projectID)
}
